import { TournamentDTO } from '../../../src-shared/TournamentDTO';

interface Props {
  tournament: TournamentDTO;
}

export default function TournamentReport({ tournament }: Props) {
  const totalEntries = tournament.brackets.reduce((sum, b) => sum + b.competitorNames.length, 0);
  const uniqueCompetitors = new Set(tournament.brackets.flatMap(b => b.competitorNames)).size;
  const date = new Date(tournament.date).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  return (
    <div style={{ fontFamily: 'Helvetica, Arial, sans-serif', background: 'white', color: '#000', padding: '40px', width: '816px', boxSizing: 'border-box' }}>

      {/* Branding */}
      <div style={{ textAlign: 'right', fontSize: '10px', color: '#aaa', marginBottom: '16px' }}>
        Generated by BracketBuddy
      </div>

      {/* Header */}
      <div style={{ textAlign: 'center', marginBottom: '16px' }}>
        <div style={{ fontSize: '28px', fontWeight: 'bold' }}>{tournament.name}</div>
        <div style={{ fontSize: '14px', color: '#555', marginTop: '4px' }}>{date}</div>
      </div>

      {/* Summary */}
      <div style={{ fontSize: '14px', marginBottom: '24px', lineHeight: '1.7' }}>
        <div>Classes: {tournament.brackets.length}</div>
        <div>Unique competitors: {uniqueCompetitors}</div>
        <div>Total entries: {totalEntries}</div>
      </div>

      {/* Per-bracket sections */}
      {tournament.brackets.map((bracket) => {
        const weightLabel = bracket.weightLimit === 'Superheavyweight'
          ? 'Superheavyweight'
          : `${bracket.weightLimit} lbs`;
        const title = `${bracket.gender} ${bracket.experienceLevel} — ${weightLabel} — ${bracket.hand} Hand`;

        return (
          <div
            key={bracket.id}
            style={{ marginBottom: '16px', breakInside: 'avoid', pageBreakInside: 'avoid' }}
          >
            <div style={{ fontSize: '15px', fontWeight: 'bold', borderBottom: '1px solid #aaa', paddingBottom: '4px', marginBottom: '6px' }}>
              {title}
            </div>
            <div style={{ fontSize: '13px', color: '#555', marginBottom: '6px' }}>
              Entries: {bracket.competitorNames.length}
            </div>
            <div style={{ fontSize: '13px', color: '#333', lineHeight: '1.8' }}>
              <div>1st: {bracket.firstPlace ?? '—'}</div>
              <div>2nd: {bracket.secondPlace ?? '—'}</div>
              <div>3rd: {bracket.thirdPlace ?? '—'}</div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
